import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro"
    },
    {
      type:"category",
      label: 'API',
      items: [
        "API/introduction",
        {
          type: "category",
          label: "Normal API",
          items: [
            "API/Normal/get-running-runtime"
          ]
        },
        {
          type: "category",
          label: "Connector required API",
          items: [
            "API/ConnectorRequired/get-extension-id",
            "API/ConnectorRequired/message"
          ]
        }
      ]
    },
    {
      type:"category",
      label: 'Configuring',
      items: [
        "Configuring/introduction",
        "Configuring/chrome-output-dir",
        "Configuring/dev-server",
        "Configuring/es-build-options",
        "Configuring/import-icon-to-userscript",
        "Configuring/manifest-path",
        "Configuring/prettier",
        "Configuring/public-dir",
        "Configuring/user-script-header",
        "Configuring/userscript-output"
      ]
    },
    {
      type: "doc",
      id: "manifest"
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
