name: Code Check

on:
  pull_request:
    branches: [main, development]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install && bun install --cwd packages/create-crx-monkey && bun install --cwd packages/crx-monkey

      - name: Run lint
        run: bun run lint

      - name: Build
        run: bun run build

  codecov:
    runs-on: ubuntu-latest
    name: codecov
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yakisova41/crx-monkey
