name: Doc Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  GIT_USER: ${{ github.actor }}:${{ github.token }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          git config --global user.email ${{ secrets.DOC_GITHUB_EMAIL }}
          git config --global user.name "yakisova41"
          yarn install
          yarn deploy
