name: Doc Deploy

on:
  push:
    branches: [main]

env:
  GIT_USER: ${{ github.actor }}:${{ github.token }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: git config
        uses: actions/checkout@v4
        run: |
          git config --global user.email ${{ github.DOC_GITHUB_EMAIL }}
          git config --global user.name "yakisova41"
          yarn install
          yarn deploy
